version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    networks:
      - rsoi_net

  games:
    build: ./games
    ports:
      - "8081:8081"
    networks:
      - rsoi_net

  sessions:
    build: ./sessions
    ports:
      - "8083:8083"
    networks:
      - rsoi_net

  transactions:
    build: ./transactions
    ports:
      - "8082:8082"
    networks:
      - rsoi_net

  statistics:
    build: ./statistics
    ports:
      - "8084:8084"
    networks:
      - rsoi_net

networks:
  rsoi_net:
